// GENERATED by scripts/gen_tables.py -- edit the script, not this file.
// Envelope time code -> per-sample level step at FS = 48000 Hz (full scale = 2^24-1).
module env_rate(
    input  logic [3:0] code,
    output logic [23:0] inc
);
    logic [23:0] rom [0:15];
    initial begin
        rom[0] = 24'd16777215;  // 0 ms
        rom[1] = 24'd174763;  // 2 ms
        rom[2] = 24'd69905;  // 5 ms
        rom[3] = 24'd34953;  // 10 ms
        rom[4] = 24'd17476;  // 20 ms
        rom[5] = 24'd6991;  // 50 ms
        rom[6] = 24'd3495;  // 100 ms
        rom[7] = 24'd1748;  // 200 ms
        rom[8] = 24'd1165;  // 300 ms
        rom[9] = 24'd699;  // 500 ms
        rom[10] = 24'd466;  // 750 ms
        rom[11] = 24'd350;  // 1000 ms
        rom[12] = 24'd233;  // 1500 ms
        rom[13] = 24'd175;  // 2000 ms
        rom[14] = 24'd117;  // 3000 ms
        rom[15] = 24'd70;  // 5000 ms
    end
    assign inc = rom[code];
endmodule
