"""Generate the lookup-table RTL: sine_table.sv, note_table.sv, env_rate.sv.

    py scripts/gen_tables.py

Tables are emitted as initialised arrays (not case statements): synthesis infers the same ROM,
and Icarus looks entries up in constant time instead of walking a 256-way case.
"""
import math
from pathlib import Path

from synthdefs import ENV_BITS, ENV_TIMES_MS, FS, midi_hz, midi_name, tuning_word

RTL = Path(__file__).resolve().parent.parent / "rtl"
HEADER = "// GENERATED by scripts/gen_tables.py -- edit the script, not this file.\n"


def rom_module(name: str, doc: str, addr_bits: int, data_bits: int, signed: bool,
               in_port: str, out_port: str, entries: list[tuple[int, str]]) -> str:
    sign = "signed " if signed else ""
    depth = 1 << addr_bits
    body = []
    for value, comment in entries:
        lit = f"-{data_bits}'sd{-value}" if value < 0 else f"{data_bits}'{'s' if signed else ''}d{value}"
        body.append((lit, comment))
    lines = [f"        rom[{i}] = {lit};" + (f"  // {c}" if c else "") for i, (lit, c) in enumerate(body)]
    return (HEADER + doc +
            f"module {name}(\n"
            f"    input  logic [{addr_bits - 1}:0] {in_port},\n"
            f"    output logic {sign}[{data_bits - 1}:0] {out_port}\n"
            ");\n"
            f"    logic {sign}[{data_bits - 1}:0] rom [0:{depth - 1}];\n"
            "    initial begin\n" + "\n".join(lines) + "\n"
            "    end\n"
            f"    assign {out_port} = rom[{in_port}];\n"
            "endmodule\n")


def sine_table() -> str:
    entries = [(round(32767 * math.sin(2 * math.pi * i / 256)), "") for i in range(256)]
    return rom_module("sine_table", "// One cycle of sine, 256 entries, signed 16-bit full scale.\n",
                      8, 16, True, "addr", "value", entries)


def note_table() -> str:
    entries = [(tuning_word(midi_hz(n)), f"{midi_name(n):<4} {midi_hz(n):10.3f} Hz") for n in range(128)]
    return rom_module("note_table", f"// MIDI note -> 32-bit phase increment at FS = {FS} Hz (note 69 = A4 = 440 Hz).\n",
                      7, 32, False, "note", "tuning_word", entries)


def env_rate() -> str:
    full = 2**ENV_BITS - 1
    entries = [(full if ms == 0 else max(1, round(full / (ms * FS / 1000))), f"{ms} ms") for ms in ENV_TIMES_MS]
    return rom_module("env_rate",
                      f"// Envelope time code -> per-sample level step at FS = {FS} Hz (full scale = 2^{ENV_BITS}-1).\n",
                      4, 24, False, "code", "inc", entries)


def main():
    RTL.mkdir(exist_ok=True)
    for name, text in [("sine_table.sv", sine_table()), ("note_table.sv", note_table()), ("env_rate.sv", env_rate())]:
        (RTL / name).write_text(text, newline="\n")
        print(f"wrote rtl/{name}")


if __name__ == "__main__":
    main()
